web:
  user-agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36'
  endpoints:
    user-profile: '/profile/{name}'
    game-data-hashes: '/gamedata/hashes'
    game-data-hashes-2: '/gamedata/hashes2'
anti-bobba:
  active: false
  localized: true
  inject:
  auto-list: []